openapi: 3.0.0

paths:
  /account/{accountID}:
    put:
      summary: This endpoint creates an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: string
                name:
                  type: string
                money_amount:
                  type: number
                business_info:
                  type: string
                monthly_salary:
                  type: number
                daily_transactions:
                  type: number
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putNewAccount/invocations"
        httpMethod: "POST"