AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: My Lambda Resources
Resources:
  PutUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: putAccount
      Environment:
        Variables:
          USERS_TABLE: !Ref AccountsTable
      Handler: account.putAccount
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AccountsTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref AccountsAPI
            Path: "/account/{accountID}"
            Method: PUT

  AccountsAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: accounts-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: accounts-app
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S